version: 2

models:
  - name: fct_daily_trips
    description: Daily aggregated taxi trip metrics
    columns:
      - name: trip_date
        description: Date of trips
        tests:
          - not_null
      - name: total_trips
        description: Number of trips
      - name: total_revenue
        description: Total revenue from all trips

  - name: fct_location_stats
    description: Trip statistics by location
    columns:
      - name: location_id
        description: Location zone ID
      - name: location_type
        description: Whether this is a pickup or dropoff location
      - name: trip_count
        description: Number of trips at this location
